apiVersion: apps/v1
kind: Deployment
metadata:
  name: land-calc
  labels:
    app: land-calc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: land-calc
  template:
    metadata:
      labels:
        app: land-calc
    spec:
      containers:
      - name: land-calc
        image: rg.fr-par.scw.cloud/iokrono/land-calc
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10